services:
  app:
    build: .
    image: dummy-docker-app/app
    container_name: backend
    ports:
      - 3000:3000
    volumes:
      - /.pickcel:/.pickcel
    links:
      - mongo
    depends_on:
      - mongo
      - redis
    restart: always
  mongo:
    build: mongo
    image: dummy-docker-app/mongo
    container_name: mongo
    ports:
      - 27107:27107
    volumes:
      - /data/db:/data/db
    restart: always
  redis:
    build: redis
    image: dummy-docker-app/redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always
