services:
  app:
    build: .
    image: dummy-docker-app/app
    container_name: dummy-docker-app-app
    ports:
      - 3000:3000
    volumes:
      - /.pickcel:/.pickcel
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
  mongo:
    build: mongo
    image: dummy-docker-app/mongo
    container_name: dummy-docker-app-mongo
    ports:
      - 27107:27107
    volumes:
      - /data/db:/data/db
    restart: always
