services:
  app:
    container_name: dummy-docker-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - /.pickcel:/.pickcel
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
  mongo:
    container_name: mongo
    build: mongo
    ports:
      - 27107:27107
    volumes:
      - /data/db:/data/db
    restart: always