services:
  nginx:
    build: nginx
    image: dummy/nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - 80:80
    restart: always

  backend:
    build: .
    image: dummy/backend
    container_name: backend
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - redis
    restart: always

  mongo:
    build: mongo
    image: dummy/mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB: ${MONGO_DB}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27107:27107
    volumes:
      - ./.mongo-data:/data/db
    restart: always

  redis:
    build: redis
    image: dummy/redis
    container_name: redis
    ports:
      - 6379:6379
    restart: always
